/*******************************************************************************
* File Name: cyfitter_cfg.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* This file provides basic startup and mux configration settings
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef CYFITTER_CFG_H
#define CYFITTER_CFG_H

#include "cytypes.h"

extern void cyfitter_cfg(void);

/* Analog Set/Unset methods */
extern void SetAnalogRoutingPumps(uint8 enabled);
extern void Front_CliffMux_Set(uint8 channel);
extern void Front_CliffMux_Unset(uint8 channel);
/* Front_CliffMux__addrTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern uint8 CYXDATA * const CYCODE Front_CliffMux__addrTable[4];
/* Front_CliffMux__maskTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern const uint8 CYCODE Front_CliffMux__maskTable[4];
extern void Rear_CliffMux_Set(uint8 channel);
extern void Rear_CliffMux_Unset(uint8 channel);
/* Rear_CliffMux__addrTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern uint8 CYXDATA * const CYCODE Rear_CliffMux__addrTable[4];
/* Rear_CliffMux__maskTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern const uint8 CYCODE Rear_CliffMux__maskTable[4];
extern void Front_AMuxSeq_DisconnectAll(void);
extern void Front_AMuxSeq_Next(void);
extern int8 Front_AMuxSeq_curChannel;
extern void Rear_AMuxSeq_DisconnectAll(void);
extern void Rear_AMuxSeq_Next(void);
extern int8 Rear_AMuxSeq_curChannel;


#endif /* CYFITTER_CFG_H */

/*[]*/
